---
platform: linux

image_resource:
  type: docker-image
  source: {repository: golang, tag: "1.8"}

inputs:
- name: concourse-git-phlow
- name: cgp-version

outputs:
- name: concourse-git-phlow-artifacts

run:
  path: concourse-git-phlow/ci/scripts/build.sh