---
platform: linux

image_resource:
  type: docker-image
  source: {repository: golang, tag: "1.8"}

inputs:
- name: concourse-git-phlow

outputs:
- name: repo-assets

run:
  path: concourse-git-phlow/ci/scripts/build.sh