---
platform: linux

image_resource:
  type: docker-image
  source: {repository: golang, tag: "1.8"}

inputs:
- name: tollgate
- name: concourse-git-phlow
- name: cgp-version
run:
  path: tollgate/ci/scripts/test.sh