resource_types:
#PIP RESOURCE TYPE
- name: pip
  type: docker-image
  source:
    repository: groenborg/concourse-git-phlow
    tag: '1.0.0'

#SLACK RESOURCE TYPE
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
#PIP RESOURCE
#running the pretested integration
- name: pretested-integration
  type: pip
  source:
    prefixready: ready/
    prefixwip: wip/
    master: master
    url: https://github.com/Praqma/concourse-git-phlow.git
    username: {{github-username}}
    password: {{github-password}}

#IMPORT THE BASE GIT RESOURCE SO WE ALWAYS HAVE THE BUILD FROM MASTER
#DEPENDING ON THE TASK, ONLY CGP IS NECESSARY
- name: concourse-git-phlow
  type: git
  source:
    uri: https://github.com/Praqma/concourse-git-phlow.git
    branch: master
    username: {{github-username}}
    password: {{github-password}}

- name: cgp-version
  type: semver
  source:
    driver: git
    uri: git@github.com:Praqma/concourse-git-phlow.git
    private_key: {{github-private-key}} 
    branch: version
    file: version

- name: docker-image-builder
  type: docker-image
  source:
    repository: groenborg/concourse-git-phlow
    username: {{docker-username}}
    password: {{docker-password}}
  
#SLACK NOTIFICATION
- name: slack-alert
  type: slack-notification
  source:
    url: {{slack-url}}

jobs:

#basic unit test run with pip
#triggers resource and puts when successfull
- name: unit-test-run
  plan:
  - get: pretested-integration
    trigger: true
  - get: concourse-git-phlow
  - task: run-test
    file: concourse-git-phlow/ci/tasks/test.yml
    on_failure:
      put: slack-alert
      params:
        text: |
            unit-test-run passed
            https://concourse.bosh.praqma.cloud/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
  - put: pretested-integration
    params:
      repository: pretested-integration
     
- name: build-docker-image
  plan:
  - get: concourse-git-phlow
    passed: [unit-test-run]
    trigger: true
  - get: cgp-version
  - get: docker-image-builder
  - task: build-assets
    file: concourse-git-phlow/ci/tasks/build.yml
  - put: cgp-version
    params: {bump: patch}
  - put: docker-image-builder
    params:
        build: concourse-git-phlow-artifacts
        tag: cgp-version/version
        tag_as_latest: true
    
