resource_types:
- name: pip
  type: docker-image
  source:
    repository: groenborg/concourse-git-phlow

resources:
#PIP RESOURCE
#running the pretested integration
#- name: pretested-integration
#  type: pip
#  source:
#    prefixready: ready/
#    prefixwip: wip/
#    master: master
#    url: https://github.com/Praqma/concourse-git-phlow.git
#    username: {{github-username}}
#    password: {{github-password}}


#IMPORT THE BASE GIT RESOURCE SO WE ALWAYS HAVE THE BUILD FROM MASTER
#DEPENDING ON THE TASK, ONLY CGP IS NECESSARY
- name: concourse-git-phlow
  type: git
  source:
    uri: https://github.com/Praqma/concourse-git-phlow.git
    branch: master
    username: {{github-username}}
    password: {{github-password}}

- name: cgp-version
  type: semver
  source:
    driver: git
    uri: https://github.com/Praqma/concourse-git-phlow.git
    username: {{github-username}}
    password: {{github-password}}
    branch: version
    file: version

- name: docker-image-builder
  type: docker-image
  source:
    repository: groenborg/concourse-git-phlow
    username: {{docker-username}}
    password: {{docker-password}}
  
    

jobs:

#basic unit test run with pip
#triggers resource and puts when successfull
- name: unit-test-run
  plan:  
  - get: concourse-git-phlow
  - task: run-test
    file: concourse-git-phlow/ci/tasks/test.yml

- name: create-docker-resource
  plan:
  - get: concourse-git-phlow
    
    
  - get: cgp-version 
  - get: docker-image-builder
  - task: build-assets
    config:
     platform: linux
     image_resource:
       type: docker-image
       source:
         repository: golang
         tag: '1.8'
     inputs:
       - name: concourse-git-phlow  
     run:
       path: sh
       args:
       - -exc
       - |
        ls
        set -e -u -x

        
        

        # RESOLVE DEPENDENCIES - TEST AND PRODUCTION
        
        go get -d -t -v ./...


        export GOOS=linux
        export GOARCH=amd64

        go build -o concourse-git-phlow/assets/check concourse-git-phlow/check/check.go
        go build -o concourse-git-phlow/assets/in concourse-git-phlow/in/in.go
        go build -o concourse-git-phlow/assets/out concourse-git-phlow/out/out.go

        chmod +x concourse-git-phlow/assets/check
        chmod +x concourse-git-phlow/assets/in
        chmod +x concourse-git-phlow/assets/out
        cd concourse-git-phlow
        ls 
        cd assets
        ls
        
        

         
  - put: docker-image-builder
    params:
        build: concourse-git-phlow
        tag: cgp-version/version

    
